### ISSUE TITLE
feat(dashboard): post layout and infinite scroll

### ISSUE THREAD

**Issue by nicobao** [zkorum/zkorum#1]
![Dashboard post](https://github.com/zkorum/zkorum/assets/46368291/8db0cfee-dc0a-48f8-b306-79f33d1a0680)

**Comment by Marob-nod** [comment]
![image](https://github.com/zkorum/zkorum/assets/79056820/38126809-262e-4d8e-bee9-236413efdc3e)

**Comment by nicobao** [comment]
Thanks for your work, that looks good!

Some remarks:
- I like how you re-positioned the last updated date and visibility on the right!
- I love the green icon you've found for showing that current logged-in user is eligible!
- speaking of user logging-in, yes, the user will show on the top-left corner. I am currently finishing implementing that.
- we will write "ESSEC" instead of essec.edu and such, for the organization we know (hard-coded in the backend from the domain name) - but for the rest (like gourou.fr) it will be the URL as you suggested. In general, don't worry about that - it is just for info.
- "Evaluation teacher A" - could be a new "type" of post with the star mechanism. We won't implement it for now. If someone wants to ask this kind of question, they would write "Do you like attending teacher A classes?" And people would respond "Yes" or "No".
- That being said, "Evaluation teacher A" is a bad example, because we will not allow targeting individuals directly.
- I realize it would be nice to have an excerpt of the content of the post right below the title of the post. Exactly like in teamblind.com
- For Discussions, I realize we can replicate teamblind.com design. We do not need the part with "Icon - 5 participants - Open until 21/08". It is redundant with the # of comment below.
- Logo "statut du createur du sondage": it is not gonna be scalable. Which logo would we find for credential "attending Macro-Economy class"? It's too early for now.
- Instead of this Logo, the logo should be the logo of the group - here ESSEC. If we don't have it in our database, it will just be a generic question mark logo for now. We can figure that out later.
- We still need to show the credentials of the one who created the post, AND the eligibility credentials of the respondents. I suggest the following approach:
    - From: a student
    - To: students 
With plain text, small characters, no icon for the alpha product. We could add this below "essec.edu" in small characters, like I did in my initial design.

The alpha version product's design is very close to that of teamblind.com so I suggest largely taking inspiration from them.
You can also look at linkedin.com when in doubt. It's OK to not have an original design for now, we just want one that works.

I suggest that you start coding it, I don't expect to go into much details in terms of CSS for the Alpha product, so the default CSS style from Material UI may dictate how things look and consequently it may change the design a little bit.

I had started something a few weeks ago, it's there: https://github.com/zkorum/zkorum/blob/f32eb1d3c41d8c447b9e30426507858713279d48/services/front/src/components/dashboard/Post.tsx#L8

This "Post" will have to be added in place of the Lorem ipsum here: https://github.com/zkorum/zkorum/blob/f32eb1d3c41d8c447b9e30426507858713279d48/services/front/src/components/dashboard/Dashboard.tsx#L7

Again thank you for your contribution!
